<?php

header('Content-Type: application/json');

require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/db.php';

function response($success, $message)
{
    echo json_encode([
        'success' => $success,
        'message' => $message
    ]);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    response(false, 'Invalid request.');
}

$id = (int)($_POST['id'] ?? 0);

if ($id <= 0) {
    response(false, 'Invalid ID.');
}

/*
|--------------------------------------------------------------------------
| Prevent deleting auto generated records
|--------------------------------------------------------------------------
*/
$check = mysqli_prepare($con,"
    SELECT isAutoGenerated
    FROM eventHolidayMaster
    WHERE id=?
    LIMIT 1
");

mysqli_stmt_bind_param($check,'i',$id);
mysqli_stmt_execute($check);
$result = mysqli_stmt_get_result($check);
$row = mysqli_fetch_assoc($result);

if (!$row) {
    response(false,'Record not found.');
}

if ((int)$row['isAutoGenerated'] === 1) {
    response(false,'System generated record cannot be deleted.');
}

/*
|--------------------------------------------------------------------------
| Delete
|--------------------------------------------------------------------------
*/
$stmt = mysqli_prepare($con,"
    DELETE FROM eventHolidayMaster
    WHERE id=?
");

mysqli_stmt_bind_param($stmt,'i',$id);

if (mysqli_stmt_execute($stmt)) {
    response(true,'Record deleted successfully.');
}

response(false,'Unable to delete record.');