CREATE TABLE IF NOT EXISTS instagramSettings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    metaAppId VARCHAR(191) NOT NULL DEFAULT '',
    metaAppSecret TEXT NOT NULL,
    redirectUrl VARCHAR(255) NOT NULL DEFAULT '',
    isActive TINYINT(1) NOT NULL DEFAULT 1,
    createdBy INT UNSIGNED NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS instagramAccounts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    createdBy INT UNSIGNED NOT NULL DEFAULT 0,
    instagramUserId VARCHAR(64) NOT NULL DEFAULT '',
    facebookPageId VARCHAR(64) NOT NULL DEFAULT '',
    username VARCHAR(180) NOT NULL DEFAULT '',
    accessToken TEXT NOT NULL,
    tokenExpiry DATETIME NULL DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'connected',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniqInstagramUserId (instagramUserId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
