CREATE TABLE IF NOT EXISTS payrollSettings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    payrollCycleType VARCHAR(30) NOT NULL DEFAULT 'monthly',
    cycleStartDay TINYINT UNSIGNED NOT NULL DEFAULT 1,
    cycleEndDay TINYINT UNSIGNED NOT NULL DEFAULT 31,
    paidDaysBasis VARCHAR(30) NOT NULL DEFAULT 'calendar',
    fixedPaidDays DECIMAL(6,2) NOT NULL DEFAULT 30.00,
    monthlyPaidLeaveDays DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    monthlyPaidLeaveCarryForward TINYINT(1) NOT NULL DEFAULT 0,
    monthlyPaidLeaveCarryForwardLimit DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    enableBirthdayPaidLeave TINYINT(1) NOT NULL DEFAULT 1,
    prorateSalaryFromJoiningDate TINYINT(1) NOT NULL DEFAULT 1,
    enableProbationLeaveRule TINYINT(1) NOT NULL DEFAULT 1,
    probationDays SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    probationLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    enableNoticePeriodLeaveRule TINYINT(1) NOT NULL DEFAULT 0,
    noticeLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    includePointPayrollDeduction TINYINT(1) NOT NULL DEFAULT 0,
    pointDeductionThreshold DECIMAL(10,2) NOT NULL DEFAULT 100.00,
    pointDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 10.00,
    compoundPointDeduction TINYINT(1) NOT NULL DEFAULT 1,
    includeProvidentFund TINYINT(1) NOT NULL DEFAULT 0,
    providentFundPercent DECIMAL(8,2) NOT NULL DEFAULT 12.00,
    providentFundWageCeiling DECIMAL(12,2) NOT NULL DEFAULT 15000.00,
    providentFundBasis VARCHAR(20) NOT NULL DEFAULT 'basic',
    includeEsic TINYINT(1) NOT NULL DEFAULT 0,
    esicEmployeePercent DECIMAL(8,2) NOT NULL DEFAULT 0.75,
    esicWageLimit DECIMAL(12,2) NOT NULL DEFAULT 21000.00,
    includeProfessionalTax TINYINT(1) NOT NULL DEFAULT 0,
    professionalTaxAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    includeIncomeTaxTds TINYINT(1) NOT NULL DEFAULT 0,
    incomeTaxTdsType VARCHAR(20) NOT NULL DEFAULT 'fixed',
    incomeTaxTdsAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    incomeTaxTdsPercent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    includeGst TINYINT(1) NOT NULL DEFAULT 0,
    gstPercent DECIMAL(8,2) NOT NULL DEFAULT 18.00,
    salaryBase VARCHAR(40) NOT NULL DEFAULT 'netSalary',
    standardWorkingHours DECIMAL(6,2) NOT NULL DEFAULT 8.00,
    includeApprovedOvertime TINYINT(1) NOT NULL DEFAULT 1,
    overtimeMultiplier DECIMAL(8,2) NOT NULL DEFAULT 1.50,
    includeManualDeductions TINYINT(1) NOT NULL DEFAULT 1,
    includeFixedEmployeeDeduction TINYINT(1) NOT NULL DEFAULT 1,
    includeApprovedExpenses TINYINT(1) NOT NULL DEFAULT 1,
    includeSyncedCommissionBonus TINYINT(1) NOT NULL DEFAULT 1,
    approvedPaidLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    approvedUnpaidLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    informedLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    uninformedLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    halfDayDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 50.00,
    absentAsUninformedLeave TINYINT(1) NOT NULL DEFAULT 1,
    pendingLeaveAsInformed TINYINT(1) NOT NULL DEFAULT 1,
    roundingRule VARCHAR(30) NOT NULL DEFAULT 'nearest_rupee',
    setupCompleted TINYINT(1) NOT NULL DEFAULT 0,
    isActive TINYINT(1) NOT NULL DEFAULT 1,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE payrollSettings
    ADD COLUMN IF NOT EXISTS monthlyPaidLeaveDays DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS monthlyPaidLeaveCarryForward TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS monthlyPaidLeaveCarryForwardLimit DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS enableBirthdayPaidLeave TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS prorateSalaryFromJoiningDate TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS enableProbationLeaveRule TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS probationDays SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS probationLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN IF NOT EXISTS enableNoticePeriodLeaveRule TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS noticeLeaveDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN IF NOT EXISTS includePointPayrollDeduction TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pointDeductionThreshold DECIMAL(10,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN IF NOT EXISTS pointDeductionPercent DECIMAL(8,2) NOT NULL DEFAULT 10.00,
    ADD COLUMN IF NOT EXISTS compoundPointDeduction TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS includeProvidentFund TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS providentFundPercent DECIMAL(8,2) NOT NULL DEFAULT 12.00,
    ADD COLUMN IF NOT EXISTS providentFundWageCeiling DECIMAL(12,2) NOT NULL DEFAULT 15000.00,
    ADD COLUMN IF NOT EXISTS providentFundBasis VARCHAR(20) NOT NULL DEFAULT 'basic',
    ADD COLUMN IF NOT EXISTS includeEsic TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS esicEmployeePercent DECIMAL(8,2) NOT NULL DEFAULT 0.75,
    ADD COLUMN IF NOT EXISTS esicWageLimit DECIMAL(12,2) NOT NULL DEFAULT 21000.00,
    ADD COLUMN IF NOT EXISTS includeProfessionalTax TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS professionalTaxAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS includeIncomeTaxTds TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS incomeTaxTdsType VARCHAR(20) NOT NULL DEFAULT 'fixed',
    ADD COLUMN IF NOT EXISTS incomeTaxTdsAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS incomeTaxTdsPercent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS includeGst TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gstPercent DECIMAL(8,2) NOT NULL DEFAULT 18.00;

INSERT INTO routesMaster (
    routePath,
    pageFile,
    routeTitle,
    moduleName,
    layoutType,
    isPublic,
    isMenuVisible,
    isActive,
    sortOrder
)
SELECT
    '/payroll-setup',
    '/pages/payroll-setup.php',
    'Payroll Setup',
    'HRMS',
    'admin',
    0,
    1,
    1,
    85
WHERE NOT EXISTS (
    SELECT 1
    FROM routesMaster
    WHERE routePath = '/payroll-setup'
);
