<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!function_exists('generateCandidateAcknowledgmentPdf')) {

function generateCandidateAcknowledgmentPdf(array $candidate): string
{
    $uploadDir = __DIR__ . '/../uploads/acknowledgment-pdf/';

    if (!is_dir($uploadDir)) {
        mkdir($uploadDir, 0777, true);
    }

    $candidateId = (int)($candidate['id'] ?? 0);

    $fileName = 'candidate_' . $candidateId . '_' . time() . '.pdf';
    $fullPath = $uploadDir . $fileName;

    $name = htmlspecialchars($candidate['fullName'] ?? '-');
    $signatureFile = (string) ($candidate['signatureFile'] ?? '');
    $signatureHtml = '';

    if ($signatureFile !== '') {

        $signaturePath = __DIR__ . '/..' . $signatureFile;

        if (file_exists($signaturePath)) {

            $ext = strtolower(pathinfo($signaturePath, PATHINFO_EXTENSION));
            $mime = ($ext === 'png') ? 'image/png' : 'image/jpeg';

            $base64 = base64_encode(file_get_contents($signaturePath));

            $signatureHtml = '
                <div style="margin-top:25px;">
                    <strong>Candidate Signature:</strong><br>
                    <img src="data:' . $mime . ';base64,' . $base64 . '" style="height:60px; margin-top:8px;">
                </div>
            ';
        }
    }
    
    /*
    |--------------------------------------------------------------------------
    | Load Dynamic Terms & Conditions
    |--------------------------------------------------------------------------
    */
    
    $configPath = __DIR__ . '/../storage/basic-config.json';
    
    $termsAndConditions = '
    <p>No terms & conditions configured.</p>
    ';
    
    if (file_exists($configPath)) {
    
        $configData = json_decode(
            file_get_contents($configPath),
            true
        );
    
        if (
            !empty(
                $configData['terms_and_conditions_html']
            )
        ) {
    
            $termsAndConditions =
                $configData['terms_and_conditions_html'];
    
        }
    
    }
    $role = htmlspecialchars($candidate['appliedRole'] ?? '-');
    $salary = htmlspecialchars($candidate['finalSalary'] ?? '-');
    $joiningDate = !empty($candidate['joiningDate'])
        ? date('d M Y', strtotime($candidate['joiningDate']))
        : '-';

    $submittedAt = !empty($candidate['acknowledgmentSubmittedAt'])
        ? date('d M Y h:i A', strtotime($candidate['acknowledgmentSubmittedAt']))
        : date('d M Y h:i A');

    $html = '
    <html>
    <head>
    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            color:#222;
            font-size:14px;
            line-height:1.5;
            padding:30px;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #111;
            padding-bottom:10px;
            margin-bottom:25px;
        }

        .title{
            font-size:24px;
            font-weight:bold;
        }

        .sub{
            font-size:12px;
            color:#666;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-bottom:25px;
        }

        th,td{
            border:1px solid #ddd;
            padding:8px 10px;
            text-align:left;
        }

        th{
            background:#f3f3f3;
            width:35%;
        }

        .section{
            margin-top:18px;
            margin-bottom:10px;
            font-size:16px;
            font-weight:bold;
            color:#111;
        }

        .box{
            border:1px solid #ddd;
            padding:14px;
            background:#fafafa;
        }

        .footer{
            margin-top:40px;
            font-size:12px;
            color:#666;
            text-align:center;
            border-top:1px solid #ddd;
            padding-top:10px;
        }
        .terms-content h1{
            font-size:18px;
            margin:12px 0 8px;
        }
        
        .terms-content h2{
            font-size:15px;
            margin:10px 0 6px;
        }
        
        .terms-content h3{
            font-size:13px;
            margin:8px 0 5px;
        }
        
        .terms-content p{
            margin:5px 0;
        }
        
        .terms-content ul{
            margin-top:5px;
            padding-left:20px;
        }
        
        .terms-content li{
            margin-bottom:4px;
        }
    </style>
    </head>
    <body>

        <div class="header">
            <div class="title">Candidate Acknowledgment Letter</div>
            <div class="sub">Generated by HRMS Onboarding System</div>
        </div>

        <div class="section">Candidate Details</div>

        <table>
            <tr><th>Full Name</th><td>'.$name.'</td></tr>
            <tr><th>Role</th><td>'.$role.'</td></tr>
            <tr><th>Salary</th><td>'.$salary.'</td></tr>
            <tr><th>Joining Date</th><td>'.$joiningDate.'</td></tr>
            <tr><th>Submitted At</th><td>'.$submittedAt.'</td></tr>
        </table>

        <div class="section">
            Terms & Conditions
        </div>
        
        <div class="box terms-content">
            '.$termsAndConditions.'
        </div>

        <div class="section">Candidate Declaration</div>

        <div class="box" style="font-size:14px; line-height:1.7;">

            <span style="
                display:inline-block;
                width:18px;
                height:18px;
                line-height:18px;
                text-align:center;
                border:2px solid #111;
                background:#ffffff;
                color:#16a34a;
                font-size:12px;
                font-weight:bold;
                margin-right:8px;
                vertical-align:middle;
            ">&#10004;</span>

            <span style="vertical-align:middle;">
                I hereby acknowledge and accept the terms of employment and confirm that I have submitted my onboarding details through the official HRMS portal.
            </span>

        </div>

       <div style="margin-top:35px;">
            <strong>Digitally Accepted By:</strong> '.$name.'<br>
            <strong>Date:</strong> '.date('d M Y h:i A').'
            '.$signatureHtml.'
        </div>

        <div class="footer">
            This is a system generated document. No physical signature required.
        </div>

    </body>
    </html>
    ';

    $options = new Options();
    $options->set('isRemoteEnabled', true);

    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    file_put_contents($fullPath, $dompdf->output());

    return $fullPath;
}

}

?>